first_name       = input("enter your first name")
last_name        = input("enter your last name")
date_of_birth    = input("enter your date of birth")
email_id=input("enter your email")
higher_education = input("enter your higher education details ")
intermediate       = input("enter your +2 details")
ssc = input("enter your school name")
mobile_number    = input("enter your mobile number")
hobbies       = input("enter your hobbies")

firstname="FIRST NAME".ljust(15)
lastname="LAST NAME".ljust(15)
dob="DATE OF BIRTH".ljust(15)
email="EMAIL".ljust(15)
btech="BTECH".ljust(15)
inter="INTERMEDIATE".ljust(15)
ssc="SSCl".ljust(15)
mobile="MOBILE NUMBER".ljust(15)
hobbies="HOBBIEs".ljust(15)

print(firstname,":",first_name)
print(lastname,":",last_name)
print(dob,":",date_of_birth)
print(email,":",email_id)
print(btech,":",higher_education)
print(inter,":",intermediate)
